dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9-dev"
addons:
    apt:
        packages:
            - rabbitmq-server
env:
    - DJANGO="Django>=2.2,<2.3"
    - DJANGO="Django>=3.0,<3.1"
    - DJANGO="Django>=3.1,<3.2"
install:
    - pip install -r requirements.txt -e .
    - pip install $DJANGO
    - pip install -r build_requirements.txt
script:
    - py.test
    - flake8 domain_event_broker --max-line-length=120 --exclude=__init__.py
    - mypy domain_event_broker
    - sphinx-build -b html docs docs/_build/html
