language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
services:
    - rabbitmq
env:
    - DJANGO="Django>=1.10,<1.11"
    - DJANGO="Django>=1.11,<1.12"
install:
    - pip install -r requirements.txt -e .
    - pip install -U pytest
    - pip install $DJANGO pytest-django
script:
    - py.test
