dist: xenial
language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"
addons:
    apt:
        packages:
            - rabbitmq-server
env:
    - DJANGO="Django>=1.11,<1.12"
    - DJANGO="Django>=2.0,<2.1"
    - DJANGO="Django>=2.1,<2.2"
    - DJANGO="Django>=2.2,<2.3"
install:
    - pip install -r requirements.txt -e .
    - pip install $DJANGO
    - pip install -r build_requirements.txt
script:
    - py.test
    - flake8 domain_events --max-line-length=120 --exclude=__init__.py
    - sphinx-build -b html docs docs/_build/html
