language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
services:
    - rabbitmq
install:
    - pip install -r requirements.txt -e .
    - pip install -U pytest
    - pip install Django
script:
    - py.test --ignore domain_events/tests/django
    - python runtests.py
